version: '3.9'

services:
  postgres:
    image: postgres
    container_name: profile-service-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - ${DB_PORT}:5432

volumes:
  postgres:
